### ISSUE TITLE
Request for ComboBox functionality

### ISSUE THREAD

**Issue by closlaurie** [northwoodspd/UIA.Extensions#8]
I hope this is the right place to ask for a request.  I couldn't find anything that specifically referred to "Reqeusts"

Thank you, 

closl

**Comment by leviwilson** [comment]
Started working on this in https://github.com/northwoodspd/UIA.Extensions/compare/master...selection_items. Not complete but I've started on it. I have a handful of things to work on:

- [ ] Allow the selection of a `ListItem`
- [ ] Come up with an interface that's friendly from a consumer to expose items available to select as well as how to select them

**Comment by leviwilson** [comment]
Added in https://www.nuget.org/packages/UIA.Extensions/1.0.11
